### ISSUE TITLE
NameError: name 'feature_extraction' is not defined

### ISSUE THREAD

**Issue by so1tsuda** [BioColLab/SCREEN#2]
Hi, thanks for developing a nice tool. I'm testing the code, and seems like feature_extraction() function cannot be found anywhere in the code? 
I am guessing it's from feature_extract.py, but no such function is defined in the file. 
Is there any chance that feature_extract.py is not up to date?  

```%python 
% python predict_SCREEN.py --PDBfile ./Example/PDB_id.txt

starting to extract features
Traceback (most recent call last):
  File "predict_SCREEN.py", line 113, in <module>
    main()
  File "predict_SCREEN.py", line 84, in main
    prot_seq = feature_extraction(protein_list,'./Example/')
NameError: name 'feature_extraction' is not defined
```

Thanks!

**Comment by BioColLab** [comment]
Hi, thanks for your interest! I've uploaded the feature_extract.py file.
