### ISSUE TITLE
FileNotFoundError: ./Dataset/training_data/seqfea/all_assign.txt not found

### ISSUE THREAD

**Issue by GajulapalliNagaVyshnavi** [BioColLab/SCREEN#4]
Hi, it seems the file "./Dataset/training_data/seqfea/all_assign.txt" is missing, causing the seq_fea_generate function to fail. 
Could you please provide the file or share guidance on its expected location and format? Thank you!

**Comment by BioColLab** [comment]
Hi, thanks for your interest! Please find the file located at '/Dataset/all_assign.txt', and make sure to set the correct data path in the code when loading it.
